//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by ATTACH.RC
//
#define IDS_VERSION_STR                 1
#define IDS_STUFFIT_MENU_STR            3
#define IDS_STUFFIT_TITLE_STR           4
#define IDS_INTERNALERR_STR             5
#define IDS_MEMORYERR_STR               6
#define IDS_RESOURCEERR_STR             7
#define IDS_TOOMANYFILESERR_STR         8
#define IDS_INVALIDFILEERR_STR          9
#define IDS_COPYRIGHT_STR               10
#define IDI_MAIN                        131
#define IDD_ALADDIN_PROGRESS_DLG        137
#define IDD_OPENDLG_EXT                 138
#define IDC_MAIN_PROGRESS               1007
#define IDS_ZIP_MENU_STR                57345
#define IDS_ZIP_TITLE_STR               57346
#define IDS_ARC_MENU_STR                57347
#define IDS_ARC_TITLE_STR               57348
#define IDS_FILE_DIR_TITLE              57349
#define IDS_ALL_FILES_FILTER            57350
#define IDS_EXTRACT_HERE                57351
#define IDS_FILE_OPEN_TITLE             57352
#define IDS_FOLDER_TXT                  57353
#define IDS_ERR_OPENING                 57354
#define IDS_ERR_DECODING                57355
#define IDS_DECOMPRESS_MENU_TXT         57356
#define IDS_EXPAND_FILTER               57357
#define IDS_FREEWARE_APPENDIX           57358
#define IDS_ERR_CREATING                57359

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        139
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1008
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
