//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by OLImport.rc
//
#define IDS_IMPORT_ADDR_OPENING_ERROR   1
#define IDS_IMPORT_ADDR_OPENING_ERROR2  2
#define IDS_IMPORT_ADDR_OPENING_ERROR3  3
#define IDS_IMPORT_ADDR_OPENING_ERROR4  4
#define IDS_IMPORT_MAPI_OPEN_ERROR      5
#define IDS_IMPORT_MAPI_UNKNOWN_ERROR   6
#define IDS_IMPORT_MAIL_READING_ERROR3  7

#define IDS_PROFILE_REGISTRY_ENTRY	8
#define IDS_PROFILE_KEY_REGISTRY	9
#define IDS_IDENTITY_REGISTRY_ENTRY_1	10
#define IDS_IDENTITY_REGISTRY_ENTRY_2	11
#define IDS_PROVIDER_NAME	12
#define IDS_DEFAULT_MAIL_REG_ENTRY	13
#define IDS_ACCOUNT_NAME	14
#define IDS_PROFILE_DISPLAY_NAME	15
#define IDS_SMTP_SERVER		16
#define IDS_PROFILE_EMAIL	17
#define IDS_POP_SERVER	18
#define IDS_PROFILE_POP_USER	19
#define IDS_PROFILE_POP_SSL		20
#define IDS_IMAP_SERVER	21
#define IDS_PROFILE_IMAP_USER	22
#define IDS_PROFILE_IMAP_SSL	23
#define IDS_PROFILE_IMAP_FOLDER	24
#define IDS_PROFILE_SMTP_SSL	25
#define IDS_PROFILE_LMOS		26
#define IDS_PROFILE_SMTP_USE_AUTH	27
#define IDS_PROFILE_AUTH_METHOD		28
#define IDS_IDENTITY_SMTP_DISPLAY	29
#define IDS_IDENTITY_SMTP_EMAIL		30
#define IDS_IDENTITY_POP_USER		31
#define IDS_IDENTITY_POP_SSL	32
#define IDS_IDENTITY_IMAP_USER	33
#define IDS_IDENTITY_IMAP_SSL	34
#define IDS_IDENTITY_IMAP_ROOT_FOLDER	35
#define IDS_IDENTITY_SMTP_SSL	36
#define IDS_IDENTITY_LMOS	37
#define IDS_IDENTITY_REMOVE_WHEN_DEL	38
#define IDS_IDENTITY_EXP_DAYS	39
#define IDS_IDENTITY_USE_SICILY	40
#define	IDS_REINSTALL_OUTLOOK 41

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        101
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
