// querydefs.h
#ifndef __QUERYDEFS_H__
#define __QUERYDEFS_H__

typedef enum {
	STATUS_RECORDINCOMPLETE = 0,
	STATUS_RECORDCOMPLETE,
	STATUS_LASTRECORD,
	STATUS_QUERYCOMPLETE,
	STATUS_QUERYCANCELLED
} QUERYSTATUS;


#endif	//__QUERYDEFS_H__
