//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by imap.rc
//
#define IDD_NETWORK_TIMEOUT             3000
#define IDC_ALERT_TEXT                  3001
#define IDS_ERR_WSK_INIT_FAILED         5000
#define IDS_ERR_INVALID_MACHINE_ADDRESS 5001
#define IDS_ERR_GETTING_SOCKET          5002
#define IDS_ERR_SERVER_CONNECT          5003
#define IDS_ERR_NET_NOT_READY			5004
#define IDS_ERR_NO_WINSOCK_DLL			5005
#define IDS_ERR_WRONG_WINSOCK_VER		5006
#define IDS_ERR_GETSERVBYNAME			5007
#define IDS_ERR_GETHOSTBYADDR			5008
#define IDS_ERR_GETHOSTBYNAME			5009
#define IDS_ERR_EUDORA_NET_TO			5010
#define IDS_NET_ERR_FORMAT				5011
#define IDS_ERR_NET_READING				5012
#define IDS_ERR_NET_WRITING				5013
#define IDS_ERR_OFFLINE					5014
#define IDS_START_NET_CONNECTION		5015
#define IDS_ERR_USER_ABORTED			5016
#define IDS_ERR_CONNECTION_BROKEN		5017
#define IDS_ERR_UNEXPECTED_UNTAGGED_RESPONSE 5018
#define IDS_ERR_BAD_KEY					5019
#define IDS_ERR_BAD_RESPONSE			5020
#define IDS_ERR_NETWORK_ERROR			5021
#define IDS_ERR_NETWORK_DISCONNECTED	5022
#define IDS_IMAP_ERROR					5023
#define IDS_ERR_CONNECTION_CLOSED		5024
#define IDS_MIME_BINHEX					5025
#define IDS_ERR_NETWORK_UNINITIALIZED	5026
#define IDS_ERR_NETWORK_DOWN			5027
#define IDS_KRB4_LIBNAME				5028
#define IDS_IMAP_SERVICE				5029
#define	IDS_GSSAPI_LIBNAME				5030
#define IDS_DES_LIBNAME					5031
#define IDS_ERR_LOADING_LIBRARY			6001


// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        101
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
	