//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by QCSSL.rc
//
#define IDD_DIALOG1                     101



#define IDS_UNKNOWNERROR				200
#define IDS_CERTERR_NOCERT				201
#define IDS_CERTWARN_IGNOREBCOSTRUSTED   202
#define IDS_CERT_TRYADD					203
#define IDS_CERT_OK						204
#define	IDS_CERTERR_CHAINBAD			205 
#define	IDS_CERTERR_CHAINNOTTRUSTED		206 
#define	IDS_CERTERR_UNKNOWNROOT			207
#define	IDS_CERTERR_NAMESNOTEQUAL		208
#define	IDS_CERTERR_DATANOTFOUND		209
#define	IDS_CERTERR_UNAUTHORIZEDCA		210
#define	IDS_CERTERR_UNKNOWNCRITICALEXT	211
#define	IDS_CERTERR_UNAUTHORIZEDCERT	212
#define	IDS_CERTERR_UNKNOWNCHAINVALIDATION	213
#define IDS_CERTERR_HOSTMISMATCH			214
#define	IDS_CERTERR_ONECERTEXPIRED			215
#define	IDS_CERTERR_MANYCERTEXPIRED			216
#define	IDS_CERTERR_OVERRIDE				217
#define	IDS_CERT_SUCCESSFULPATTERNNOTALLOW	218 
#define	IDS_ERR_VERSIONINVALID		219
#define	IDS_ERR_SSL2NOTOK			220
#define	IDS_ERR_MINEXCHNONO			221
#define	IDS_ERR_MINENCRYPTIONNONO	222
#define IDS_CALG_HMAC 223
#define IDS_CALG_MD2 224
#define IDS_CALG_MD4 225
#define IDS_CALG_MD5 226
#define IDS_CALG_SHA 227
#define IDS_CALG_SHA1  228
#define IDS_CALG_MAC 229
#define IDS_ERR_PRIVATEKEYCONSTRUCTION 230
#define IDS_ERR_CERTFILE 250
#define IDS_ERR_CONNECTIONLOST 260
