@echo off
cd %1%
echo ...............................................
echo .           Starting Post Build BIND          .
echo ...............................................
..\..\BinTools\bind -p .;%windir%;%windir%\system32 -u -v Eudora.exe DirServ.dll EudoraBk.dll ISock.dll LDAP.dll LDAP32.DLL Paige32.dll Ph.dll SPELL32.DLL EudoraRes.dll EuMemMgr.dll QCUtils.dll imap.dll QCSocket.dll plstclnt.dll EuLang.dll QCSSL.dll libeay32.dll ssleay32.dll libexpat.dll x1lib.dll
echo ...............................................
echo .            Ending Post Build BIND           .
echo ...............................................

