	; Don't even think of reading this code
	; It was automatically generated by sha1-586.pl
	; Which is a perl program used to generate the x86 assember for
	; any of elf, a.out, BSDI, Win32, gaswin (for GNU as on Win32) or Solaris
	; eric <eay@cryptsoft.com>
	; 
	TITLE	sha1-586.asm
        .486
.model FLAT
_TEXT	SEGMENT
PUBLIC	_sha1_block_asm_data_order

_sha1_block_asm_data_order PROC NEAR
	mov	ecx,		DWORD PTR 12[esp]
	push	esi
	shl	ecx,		6
	mov	esi,		DWORD PTR 12[esp]
	push	ebp
	add	ecx,		esi
	push	ebx
	mov	ebp,		DWORD PTR 16[esp]
	push	edi
	mov	edx,		DWORD PTR 12[ebp]
	sub	esp,		108
	mov	edi,		DWORD PTR 16[ebp]
	mov	ebx,		DWORD PTR 8[ebp]
	mov	DWORD PTR 68[esp],ecx
	; First we need to setup the X array
$L000start:
	; First, load the words onto the stack in network byte order
	mov	eax,		DWORD PTR [esi]
	mov	ecx,		DWORD PTR 4[esi]
	bswap	eax
	bswap	ecx
	mov	DWORD PTR [esp],eax
	mov	DWORD PTR 4[esp],ecx
	mov	eax,		DWORD PTR 8[esi]
	mov	ecx,		DWORD PTR 12[esi]
	bswap	eax
	bswap	ecx
	mov	DWORD PTR 8[esp],eax
	mov	DWORD PTR 12[esp],ecx
	mov	eax,		DWORD PTR 16[esi]
	mov	ecx,		DWORD PTR 20[esi]
	bswap	eax
	bswap	ecx
	mov	DWORD PTR 16[esp],eax
	mov	DWORD PTR 20[esp],ecx
	mov	eax,		DWORD PTR 24[esi]
	mov	ecx,		DWORD PTR 28[esi]
	bswap	eax
	bswap	ecx
	mov	DWORD PTR 24[esp],eax
	mov	DWORD PTR 28[esp],ecx
	mov	eax,		DWORD PTR 32[esi]
	mov	ecx,		DWORD PTR 36[esi]
	bswap	eax
	bswap	ecx
	mov	DWORD PTR 32[esp],eax
	mov	DWORD PTR 36[esp],ecx
	mov	eax,		DWORD PTR 40[esi]
	mov	ecx,		DWORD PTR 44[esi]
	bswap	eax
	bswap	ecx
	mov	DWORD PTR 40[esp],eax
	mov	DWORD PTR 44[esp],ecx
	mov	eax,		DWORD PTR 48[esi]
	mov	ecx,		DWORD PTR 52[esi]
	bswap	eax
	bswap	ecx
	mov	DWORD PTR 48[esp],eax
	mov	DWORD PTR 52[esp],ecx
	mov	eax,		DWORD PTR 56[esi]
	mov	ecx,		DWORD PTR 60[esi]
	bswap	eax
	bswap	ecx
	mov	DWORD PTR 56[esp],eax
	mov	DWORD PTR 60[esp],ecx
	; We now have the X array on the stack
	; starting at sp-4
	mov	DWORD PTR 132[esp],esi
$L001shortcut::
	; 
	; Start processing
	mov	eax,		DWORD PTR [ebp]
	mov	ecx,		DWORD PTR 4[ebp]
	; 00_15 0
	mov	ebp,		eax
	mov	esi,		ebx
	rol	ebp,		5
	xor	esi,		edx
	and	esi,		ecx
	ror	ecx,		2
	add	ebp,		edi
	mov	edi,		DWORD PTR [esp]
	xor	esi,		edx
	lea	ebp,		DWORD PTR 1518500249[edi*1+ebp]
	add	esi,		ebp
	; 00_15 1
	mov	ebp,		esi
	mov	edi,		ecx
	rol	ebp,		5
	xor	edi,		ebx
	and	edi,		eax
	ror	eax,		2
	add	ebp,		edx
	mov	edx,		DWORD PTR 4[esp]
	xor	edi,		ebx
	lea	ebp,		DWORD PTR 1518500249[edx*1+ebp]
	add	edi,		ebp
	; 00_15 2
	mov	ebp,		edi
	mov	edx,		eax
	rol	ebp,		5
	xor	edx,		ecx
	and	edx,		esi
	ror	esi,		2
	add	ebp,		ebx
	mov	ebx,		DWORD PTR 8[esp]
	xor	edx,		ecx
	lea	ebp,		DWORD PTR 1518500249[ebx*1+ebp]
	add	edx,		ebp
	; 00_15 3
	mov	ebp,		edx
	mov	ebx,		esi
	rol	ebp,		5
	xor	ebx,		eax
	and	ebx,		edi
	ror	edi,		2
	add	ebp,		ecx
	mov	ecx,		DWORD PTR 12[esp]
	xor	ebx,		eax
	lea	ebp,		DWORD PTR 1518500249[ecx*1+ebp]
	add	ebx,		ebp
	; 00_15 4
	mov	ebp,		ebx
	mov	ecx,		edi
	rol	ebp,		5
	xor	ecx,		esi
	and	ecx,		edx
	ror	edx,		2
	add	ebp,		eax
	mov	eax,		DWORD PTR 16[esp]
	xor	ecx,		esi
	lea	ebp,		DWORD PTR 1518500249[eax*1+ebp]
	add	ecx,		ebp
	; 00_15 5
	mov	ebp,		ecx
	mov	eax,		edx
	rol	ebp,		5
	xor	eax,		edi
	and	eax,		ebx
	ror	ebx,		2
	add	ebp,		esi
	mov	esi,		DWORD PTR 20[esp]
	xor	eax,		edi
	lea	ebp,		DWORD PTR 1518500249[esi*1+ebp]
	add	eax,		ebp
	; 00_15 6
	mov	ebp,		eax
	mov	esi,		ebx
	rol	ebp,		5
	xor	esi,		edx
	and	esi,		ecx
	ror	ecx,		2
	add	ebp,		edi
	mov	edi,		DWORD PTR 24[esp]
	xor	esi,		edx
	lea	ebp,		DWORD PTR 1518500249[edi*1+ebp]
	add	esi,		ebp
	; 00_15 7
	mov	ebp,		esi
	mov	edi,		ecx
	rol	ebp,		5
	xor	edi,		ebx
	and	edi,		eax
	ror	eax,		2
	add	ebp,		edx
	mov	edx,		DWORD PTR 28[esp]
	xor	edi,		ebx
	lea	ebp,		DWORD PTR 1518500249[edx*1+ebp]
	add	edi,		ebp
	; 00_15 8
	mov	ebp,		edi
	mov	edx,		eax
	rol	ebp,		5
	xor	edx,		ecx
	and	edx,		esi
	ror	esi,		2
	add	ebp,		ebx
	mov	ebx,		DWORD PTR 32[esp]
	xor	edx,		ecx
	lea	ebp,		DWORD PTR 1518500249[ebx*1+ebp]
	add	edx,		ebp
	; 00_15 9
	mov	ebp,		edx
	mov	ebx,		esi
	rol	ebp,		5
	xor	ebx,		eax
	and	ebx,		edi
	ror	edi,		2
	add	ebp,		ecx
	mov	ecx,		DWORD PTR 36[esp]
	xor	ebx,		eax
	lea	ebp,		DWORD PTR 1518500249[ecx*1+ebp]
	add	ebx,		ebp
	; 00_15 10
	mov	ebp,		ebx
	mov	ecx,		edi
	rol	ebp,		5
	xor	ecx,		esi
	and	ecx,		edx
	ror	edx,		2
	add	ebp,		eax
	mov	eax,		DWORD PTR 40[esp]
	xor	ecx,		esi
	lea	ebp,		DWORD PTR 1518500249[eax*1+ebp]
	add	ecx,		ebp
	; 00_15 11
	mov	ebp,		ecx
	mov	eax,		edx
	rol	ebp,		5
	xor	eax,		edi
	and	eax,		ebx
	ror	ebx,		2
	add	ebp,		esi
	mov	esi,		DWORD PTR 44[esp]
	xor	eax,		edi
	lea	ebp,		DWORD PTR 1518500249[esi*1+ebp]
	add	eax,		ebp
	; 00_15 12
	mov	ebp,		eax
	mov	esi,		ebx
	rol	ebp,		5
	xor	esi,		edx
	and	esi,		ecx
	ror	ecx,		2
	add	ebp,		edi
	mov	edi,		DWORD PTR 48[esp]
	xor	esi,		edx
	lea	ebp,		DWORD PTR 1518500249[edi*1+ebp]
	add	esi,		ebp
	; 00_15 13
	mov	ebp,		esi
	mov	edi,		ecx
	rol	ebp,		5
	xor	edi,		ebx
	and	edi,		eax
	ror	eax,		2
	add	ebp,		edx
	mov	edx,		DWORD PTR 52[esp]
	xor	edi,		ebx
	lea	ebp,		DWORD PTR 1518500249[edx*1+ebp]
	add	edi,		ebp
	; 00_15 14
	mov	ebp,		edi
	mov	edx,		eax
	rol	ebp,		5
	xor	edx,		ecx
	and	edx,		esi
	ror	esi,		2
	add	ebp,		ebx
	mov	ebx,		DWORD PTR 56[esp]
	xor	edx,		ecx
	lea	ebp,		DWORD PTR 1518500249[ebx*1+ebp]
	add	edx,		ebp
	; 00_15 15
	mov	ebp,		edx
	mov	ebx,		esi
	rol	ebp,		5
	xor	ebx,		eax
	and	ebx,		edi
	ror	edi,		2
	add	ebp,		ecx
	mov	ecx,		DWORD PTR 60[esp]
	xor	ebx,		eax
	lea	ebp,		DWORD PTR 1518500249[ecx*1+ebp]
	add	ebx,		ebp
	; 16_19 16
	mov	ecx,		DWORD PTR 8[esp]
	mov	ebp,		edi
	xor	ecx,		DWORD PTR [esp]
	xor	ebp,		esi
	xor	ecx,		DWORD PTR 32[esp]
	and	ebp,		edx
	xor	ecx,		DWORD PTR 52[esp]
	ror	edx,		2
	xor	ebp,		esi
	rol	ecx,		1
	mov	DWORD PTR [esp],ecx
	lea	ecx,		DWORD PTR 1518500249[eax*1+ecx]
	mov	eax,		ebx
	add	ecx,		ebp
	rol	eax,		5
	add	ecx,		eax
	; 16_19 17
	mov	eax,		DWORD PTR 12[esp]
	mov	ebp,		edx
	xor	eax,		DWORD PTR 4[esp]
	xor	ebp,		edi
	xor	eax,		DWORD PTR 36[esp]
	and	ebp,		ebx
	xor	eax,		DWORD PTR 56[esp]
	ror	ebx,		2
	xor	ebp,		edi
	rol	eax,		1
	mov	DWORD PTR 4[esp],eax
	lea	eax,		DWORD PTR 1518500249[esi*1+eax]
	mov	esi,		ecx
	add	eax,		ebp
	rol	esi,		5
	add	eax,		esi
	; 16_19 18
	mov	esi,		DWORD PTR 16[esp]
	mov	ebp,		ebx
	xor	esi,		DWORD PTR 8[esp]
	xor	ebp,		edx
	xor	esi,		DWORD PTR 40[esp]
	and	ebp,		ecx
	xor	esi,		DWORD PTR 60[esp]
	ror	ecx,		2
	xor	ebp,		edx
	rol	esi,		1
	mov	DWORD PTR 8[esp],esi
	lea	esi,		DWORD PTR 1518500249[edi*1+esi]
	mov	edi,		eax
	add	esi,		ebp
	rol	edi,		5
	add	esi,		edi
	; 16_19 19
	mov	edi,		DWORD PTR 20[esp]
	mov	ebp,		ecx
	xor	edi,		DWORD PTR 12[esp]
	xor	ebp,		ebx
	xor	edi,		DWORD PTR 44[esp]
	and	ebp,		eax
	xor	edi,		DWORD PTR [esp]
	ror	eax,		2
	xor	ebp,		ebx
	rol	edi,		1
	mov	DWORD PTR 12[esp],edi
	lea	edi,		DWORD PTR 1518500249[edx*1+edi]
	mov	edx,		esi
	add	edi,		ebp
	rol	edx,		5
	add	edi,		edx
	; 20_39 20
	mov	edx,		DWORD PTR 16[esp]
	mov	ebp,		esi
	xor	edx,		DWORD PTR 24[esp]
	ror	esi,		2
	xor	edx,		DWORD PTR 48[esp]
	xor	ebp,		eax
	xor	edx,		DWORD PTR 4[esp]
	xor	ebp,		ecx
	rol	edx,		1
	mov	DWORD PTR 16[esp],edx
	lea	edx,		DWORD PTR 1859775393[ebx*1+edx]
	mov	ebx,		edi
	rol	ebx,		5
	add	edx,		ebp
	add	edx,		ebx
	; 20_39 21
	mov	ebx,		DWORD PTR 20[esp]
	mov	ebp,		edi
	xor	ebx,		DWORD PTR 28[esp]
	ror	edi,		2
	xor	ebx,		DWORD PTR 52[esp]
	xor	ebp,		esi
	xor	ebx,		DWORD PTR 8[esp]
	xor	ebp,		eax
	rol	ebx,		1
	mov	DWORD PTR 20[esp],ebx
	lea	ebx,		DWORD PTR 1859775393[ecx*1+ebx]
	mov	ecx,		edx
	rol	ecx,		5
	add	ebx,		ebp
	add	ebx,		ecx
	; 20_39 22
	mov	ecx,		DWORD PTR 24[esp]
	mov	ebp,		edx
	xor	ecx,		DWORD PTR 32[esp]
	ror	edx,		2
	xor	ecx,		DWORD PTR 56[esp]
	xor	ebp,		edi
	xor	ecx,		DWORD PTR 12[esp]
	xor	ebp,		esi
	rol	ecx,		1
	mov	DWORD PTR 24[esp],ecx
	lea	ecx,		DWORD PTR 1859775393[eax*1+ecx]
	mov	eax,		ebx
	rol	eax,		5
	add	ecx,		ebp
	add	ecx,		eax
	; 20_39 23
	mov	eax,		DWORD PTR 28[esp]
	mov	ebp,		ebx
	xor	eax,		DWORD PTR 36[esp]
	ror	ebx,		2
	xor	eax,		DWORD PTR 60[esp]
	xor	ebp,		edx
	xor	eax,		DWORD PTR 16[esp]
	xor	ebp,		edi
	rol	eax,		1
	mov	DWORD PTR 28[esp],eax
	lea	eax,		DWORD PTR 1859775393[esi*1+eax]
	mov	esi,		ecx
	rol	esi,		5
	add	eax,		ebp
	add	eax,		esi
	; 20_39 24
	mov	esi,		DWORD PTR 32[esp]
	mov	ebp,		ecx
	xor	esi,		DWORD PTR 40[esp]
	ror	ecx,		2
	xor	esi,		DWORD PTR [esp]
	xor	ebp,		ebx
	xor	esi,		DWORD PTR 20[esp]
	xor	ebp,		edx
	rol	esi,		1
	mov	DWORD PTR 32[esp],esi
	lea	esi,		DWORD PTR 1859775393[edi*1+esi]
	mov	edi,		eax
	rol	edi,		5
	add	esi,		ebp
	add	esi,		edi
	; 20_39 25
	mov	edi,		DWORD PTR 36[esp]
	mov	ebp,		eax
	xor	edi,		DWORD PTR 44[esp]
	ror	eax,		2
	xor	edi,		DWORD PTR 4[esp]
	xor	ebp,		ecx
	xor	edi,		DWORD PTR 24[esp]
	xor	ebp,		ebx
	rol	edi,		1
	mov	DWORD PTR 36[esp],edi
	lea	edi,		DWORD PTR 1859775393[edx*1+edi]
	mov	edx,		esi
	rol	edx,		5
	add	edi,		ebp
	add	edi,		edx
	; 20_39 26
	mov	edx,		DWORD PTR 40[esp]
	mov	ebp,		esi
	xor	edx,		DWORD PTR 48[esp]
	ror	esi,		2
	xor	edx,		DWORD PTR 8[esp]
	xor	ebp,		eax
	xor	edx,		DWORD PTR 28[esp]
	xor	ebp,		ecx
	rol	edx,		1
	mov	DWORD PTR 40[esp],edx
	lea	edx,		DWORD PTR 1859775393[ebx*1+edx]
	mov	ebx,		edi
	rol	ebx,		5
	add	edx,		ebp
	add	edx,		ebx
	; 20_39 27
	mov	ebx,		DWORD PTR 44[esp]
	mov	ebp,		edi
	xor	ebx,		DWORD PTR 52[esp]
	ror	edi,		2
	xor	ebx,		DWORD PTR 12[esp]
	xor	ebp,		esi
	xor	ebx,		DWORD PTR 32[esp]
	xor	ebp,		eax
	rol	ebx,		1
	mov	DWORD PTR 44[esp],ebx
	lea	ebx,		DWORD PTR 1859775393[ecx*1+ebx]
	mov	ecx,		edx
	rol	ecx,		5
	add	ebx,		ebp
	add	ebx,		ecx
	; 20_39 28
	mov	ecx,		DWORD PTR 48[esp]
	mov	ebp,		edx
	xor	ecx,		DWORD PTR 56[esp]
	ror	edx,		2
	xor	ecx,		DWORD PTR 16[esp]
	xor	ebp,		edi
	xor	ecx,		DWORD PTR 36[esp]
	xor	ebp,		esi
	rol	ecx,		1
	mov	DWORD PTR 48[esp],ecx
	lea	ecx,		DWORD PTR 1859775393[eax*1+ecx]
	mov	eax,		ebx
	rol	eax,		5
	add	ecx,		ebp
	add	ecx,		eax
	; 20_39 29
	mov	eax,		DWORD PTR 52[esp]
	mov	ebp,		ebx
	xor	eax,		DWORD PTR 60[esp]
	ror	ebx,		2
	xor	eax,		DWORD PTR 20[esp]
	xor	ebp,		edx
	xor	eax,		DWORD PTR 40[esp]
	xor	ebp,		edi
	rol	eax,		1
	mov	DWORD PTR 52[esp],eax
	lea	eax,		DWORD PTR 1859775393[esi*1+eax]
	mov	esi,		ecx
	rol	esi,		5
	add	eax,		ebp
	add	eax,		esi
	; 20_39 30
	mov	esi,		DWORD PTR 56[esp]
	mov	ebp,		ecx
	xor	esi,		DWORD PTR [esp]
	ror	ecx,		2
	xor	esi,		DWORD PTR 24[esp]
	xor	ebp,		ebx
	xor	esi,		DWORD PTR 44[esp]
	xor	ebp,		edx
	rol	esi,		1
	mov	DWORD PTR 56[esp],esi
	lea	esi,		DWORD PTR 1859775393[edi*1+esi]
	mov	edi,		eax
	rol	edi,		5
	add	esi,		ebp
	add	esi,		edi
	; 20_39 31
	mov	edi,		DWORD PTR 60[esp]
	mov	ebp,		eax
	xor	edi,		DWORD PTR 4[esp]
	ror	eax,		2
	xor	edi,		DWORD PTR 28[esp]
	xor	ebp,		ecx
	xor	edi,		DWORD PTR 48[esp]
	xor	ebp,		ebx
	rol	edi,		1
	mov	DWORD PTR 60[esp],edi
	lea	edi,		DWORD PTR 1859775393[edx*1+edi]
	mov	edx,		esi
	rol	edx,		5
	add	edi,		ebp
	add	edi,		edx
	; 20_39 32
	mov	edx,		DWORD PTR [esp]
	mov	ebp,		esi
	xor	edx,		DWORD PTR 8[esp]
	ror	esi,		2
	xor	edx,		DWORD PTR 32[esp]
	xor	ebp,		eax
	xor	edx,		DWORD PTR 52[esp]
	xor	ebp,		ecx
	rol	edx,		1
	mov	DWORD PTR [esp],edx
	lea	edx,		DWORD PTR 1859775393[ebx*1+edx]
	mov	ebx,		edi
	rol	ebx,		5
	add	edx,		ebp
	add	edx,		ebx
	; 20_39 33
	mov	ebx,		DWORD PTR 4[esp]
	mov	ebp,		edi
	xor	ebx,		DWORD PTR 12[esp]
	ror	edi,		2
	xor	ebx,		DWORD PTR 36[esp]
	xor	ebp,		esi
	xor	ebx,		DWORD PTR 56[esp]
	xor	ebp,		eax
	rol	ebx,		1
	mov	DWORD PTR 4[esp],ebx
	lea	ebx,		DWORD PTR 1859775393[ecx*1+ebx]
	mov	ecx,		edx
	rol	ecx,		5
	add	ebx,		ebp
	add	ebx,		ecx
	; 20_39 34
	mov	ecx,		DWORD PTR 8[esp]
	mov	ebp,		edx
	xor	ecx,		DWORD PTR 16[esp]
	ror	edx,		2
	xor	ecx,		DWORD PTR 40[esp]
	xor	ebp,		edi
	xor	ecx,		DWORD PTR 60[esp]
	xor	ebp,		esi
	rol	ecx,		1
	mov	DWORD PTR 8[esp],ecx
	lea	ecx,		DWORD PTR 1859775393[eax*1+ecx]
	mov	eax,		ebx
	rol	eax,		5
	add	ecx,		ebp
	add	ecx,		eax
	; 20_39 35
	mov	eax,		DWORD PTR 12[esp]
	mov	ebp,		ebx
	xor	eax,		DWORD PTR 20[esp]
	ror	ebx,		2
	xor	eax,		DWORD PTR 44[esp]
	xor	ebp,		edx
	xor	eax,		DWORD PTR [esp]
	xor	ebp,		edi
	rol	eax,		1
	mov	DWORD PTR 12[esp],eax
	lea	eax,		DWORD PTR 1859775393[esi*1+eax]
	mov	esi,		ecx
	rol	esi,		5
	add	eax,		ebp
	add	eax,		esi
	; 20_39 36
	mov	esi,		DWORD PTR 16[esp]
	mov	ebp,		ecx
	xor	esi,		DWORD PTR 24[esp]
	ror	ecx,		2
	xor	esi,		DWORD PTR 48[esp]
	xor	ebp,		ebx
	xor	esi,		DWORD PTR 4[esp]
	xor	ebp,		edx
	rol	esi,		1
	mov	DWORD PTR 16[esp],esi
	lea	esi,		DWORD PTR 1859775393[edi*1+esi]
	mov	edi,		eax
	rol	edi,		5
	add	esi,		ebp
	add	esi,		edi
	; 20_39 37
	mov	edi,		DWORD PTR 20[esp]
	mov	ebp,		eax
	xor	edi,		DWORD PTR 28[esp]
	ror	eax,		2
	xor	edi,		DWORD PTR 52[esp]
	xor	ebp,		ecx
	xor	edi,		DWORD PTR 8[esp]
	xor	ebp,		ebx
	rol	edi,		1
	mov	DWORD PTR 20[esp],edi
	lea	edi,		DWORD PTR 1859775393[edx*1+edi]
	mov	edx,		esi
	rol	edx,		5
	add	edi,		ebp
	add	edi,		edx
	; 20_39 38
	mov	edx,		DWORD PTR 24[esp]
	mov	ebp,		esi
	xor	edx,		DWORD PTR 32[esp]
	ror	esi,		2
	xor	edx,		DWORD PTR 56[esp]
	xor	ebp,		eax
	xor	edx,		DWORD PTR 12[esp]
	xor	ebp,		ecx
	rol	edx,		1
	mov	DWORD PTR 24[esp],edx
	lea	edx,		DWORD PTR 1859775393[ebx*1+edx]
	mov	ebx,		edi
	rol	ebx,		5
	add	edx,		ebp
	add	edx,		ebx
	; 20_39 39
	mov	ebx,		DWORD PTR 28[esp]
	mov	ebp,		edi
	xor	ebx,		DWORD PTR 36[esp]
	ror	edi,		2
	xor	ebx,		DWORD PTR 60[esp]
	xor	ebp,		esi
	xor	ebx,		DWORD PTR 16[esp]
	xor	ebp,		eax
	rol	ebx,		1
	mov	DWORD PTR 28[esp],ebx
	lea	ebx,		DWORD PTR 1859775393[ecx*1+ebx]
	mov	ecx,		edx
	rol	ecx,		5
	add	ebx,		ebp
	add	ebx,		ecx
	; 40_59 40
	mov	ecx,		DWORD PTR 32[esp]
	mov	ebp,		edx
	xor	ecx,		DWORD PTR 40[esp]
	or	ebp,		edi
	xor	ecx,		DWORD PTR [esp]
	and	ebp,		esi
	xor	ecx,		DWORD PTR 20[esp]
	rol	ecx,		1
	mov	DWORD PTR 32[esp],ecx
	lea	ecx,		DWORD PTR 2400959708[eax*1+ecx]
	mov	eax,		edx
	ror	edx,		2
	and	eax,		edi
	or	ebp,		eax
	mov	eax,		ebx
	rol	eax,		5
	add	ebp,		eax
	add	ecx,		ebp
	; 40_59 41
	mov	eax,		DWORD PTR 36[esp]
	mov	ebp,		ebx
	xor	eax,		DWORD PTR 44[esp]
	or	ebp,		edx
	xor	eax,		DWORD PTR 4[esp]
	and	ebp,		edi
	xor	eax,		DWORD PTR 24[esp]
	rol	eax,		1
	mov	DWORD PTR 36[esp],eax
	lea	eax,		DWORD PTR 2400959708[esi*1+eax]
	mov	esi,		ebx
	ror	ebx,		2
	and	esi,		edx
	or	ebp,		esi
	mov	esi,		ecx
	rol	esi,		5
	add	ebp,		esi
	add	eax,		ebp
	; 40_59 42
	mov	esi,		DWORD PTR 40[esp]
	mov	ebp,		ecx
	xor	esi,		DWORD PTR 48[esp]
	or	ebp,		ebx
	xor	esi,		DWORD PTR 8[esp]
	and	ebp,		edx
	xor	esi,		DWORD PTR 28[esp]
	rol	esi,		1
	mov	DWORD PTR 40[esp],esi
	lea	esi,		DWORD PTR 2400959708[edi*1+esi]
	mov	edi,		ecx
	ror	ecx,		2
	and	edi,		ebx
	or	ebp,		edi
	mov	edi,		eax
	rol	edi,		5
	add	ebp,		edi
	add	esi,		ebp
	; 40_59 43
	mov	edi,		DWORD PTR 44[esp]
	mov	ebp,		eax
	xor	edi,		DWORD PTR 52[esp]
	or	ebp,		ecx
	xor	edi,		DWORD PTR 12[esp]
	and	ebp,		ebx
	xor	edi,		DWORD PTR 32[esp]
	rol	edi,		1
	mov	DWORD PTR 44[esp],edi
	lea	edi,		DWORD PTR 2400959708[edx*1+edi]
	mov	edx,		eax
	ror	eax,		2
	and	edx,		ecx
	or	ebp,		edx
	mov	edx,		esi
	rol	edx,		5
	add	ebp,		edx
	add	edi,		ebp
	; 40_59 44
	mov	edx,		DWORD PTR 48[esp]
	mov	ebp,		esi
	xor	edx,		DWORD PTR 56[esp]
	or	ebp,		eax
	xor	edx,		DWORD PTR 16[esp]
	and	ebp,		ecx
	xor	edx,		DWORD PTR 36[esp]
	rol	edx,		1
	mov	DWORD PTR 48[esp],edx
	lea	edx,		DWORD PTR 2400959708[ebx*1+edx]
	mov	ebx,		esi
	ror	esi,		2
	and	ebx,		eax
	or	ebp,		ebx
	mov	ebx,		edi
	rol	ebx,		5
	add	ebp,		ebx
	add	edx,		ebp
	; 40_59 45
	mov	ebx,		DWORD PTR 52[esp]
	mov	ebp,		edi
	xor	ebx,		DWORD PTR 60[esp]
	or	ebp,		esi
	xor	ebx,		DWORD PTR 20[esp]
	and	ebp,		eax
	xor	ebx,		DWORD PTR 40[esp]
	rol	ebx,		1
	mov	DWORD PTR 52[esp],ebx
	lea	ebx,		DWORD PTR 2400959708[ecx*1+ebx]
	mov	ecx,		edi
	ror	edi,		2
	and	ecx,		esi
	or	ebp,		ecx
	mov	ecx,		edx
	rol	ecx,		5
	add	ebp,		ecx
	add	ebx,		ebp
	; 40_59 46
	mov	ecx,		DWORD PTR 56[esp]
	mov	ebp,		edx
	xor	ecx,		DWORD PTR [esp]
	or	ebp,		edi
	xor	ecx,		DWORD PTR 24[esp]
	and	ebp,		esi
	xor	ecx,		DWORD PTR 44[esp]
	rol	ecx,		1
	mov	DWORD PTR 56[esp],ecx
	lea	ecx,		DWORD PTR 2400959708[eax*1+ecx]
	mov	eax,		edx
	ror	edx,		2
	and	eax,		edi
	or	ebp,		eax
	mov	eax,		ebx
	rol	eax,		5
	add	ebp,		eax
	add	ecx,		ebp
	; 40_59 47
	mov	eax,		DWORD PTR 60[esp]
	mov	ebp,		ebx
	xor	eax,		DWORD PTR 4[esp]
	or	ebp,		edx
	xor	eax,		DWORD PTR 28[esp]
	and	ebp,		edi
	xor	eax,		DWORD PTR 48[esp]
	rol	eax,		1
	mov	DWORD PTR 60[esp],eax
	lea	eax,		DWORD PTR 2400959708[esi*1+eax]
	mov	esi,		ebx
	ror	ebx,		2
	and	esi,		edx
	or	ebp,		esi
	mov	esi,		ecx
	rol	esi,		5
	add	ebp,		esi
	add	eax,		ebp
	; 40_59 48
	mov	esi,		DWORD PTR [esp]
	mov	ebp,		ecx
	xor	esi,		DWORD PTR 8[esp]
	or	ebp,		ebx
	xor	esi,		DWORD PTR 32[esp]
	and	ebp,		edx
	xor	esi,		DWORD PTR 52[esp]
	rol	esi,		1
	mov	DWORD PTR [esp],esi
	lea	esi,		DWORD PTR 2400959708[edi*1+esi]
	mov	edi,		ecx
	ror	ecx,		2
	and	edi,		ebx
	or	ebp,		edi
	mov	edi,		eax
	rol	edi,		5
	add	ebp,		edi
	add	esi,		ebp
	; 40_59 49
	mov	edi,		DWORD PTR 4[esp]
	mov	ebp,		eax
	xor	edi,		DWORD PTR 12[esp]
	or	ebp,		ecx
	xor	edi,		DWORD PTR 36[esp]
	and	ebp,		ebx
	xor	edi,		DWORD PTR 56[esp]
	rol	edi,		1
	mov	DWORD PTR 4[esp],edi
	lea	edi,		DWORD PTR 2400959708[edx*1+edi]
	mov	edx,		eax
	ror	eax,		2
	and	edx,		ecx
	or	ebp,		edx
	mov	edx,		esi
	rol	edx,		5
	add	ebp,		edx
	add	edi,		ebp
	; 40_59 50
	mov	edx,		DWORD PTR 8[esp]
	mov	ebp,		esi
	xor	edx,		DWORD PTR 16[esp]
	or	ebp,		eax
	xor	edx,		DWORD PTR 40[esp]
	and	ebp,		ecx
	xor	edx,		DWORD PTR 60[esp]
	rol	edx,		1
	mov	DWORD PTR 8[esp],edx
	lea	edx,		DWORD PTR 2400959708[ebx*1+edx]
	mov	ebx,		esi
	ror	esi,		2
	and	ebx,		eax
	or	ebp,		ebx
	mov	ebx,		edi
	rol	ebx,		5
	add	ebp,		ebx
	add	edx,		ebp
	; 40_59 51
	mov	ebx,		DWORD PTR 12[esp]
	mov	ebp,		edi
	xor	ebx,		DWORD PTR 20[esp]
	or	ebp,		esi
	xor	ebx,		DWORD PTR 44[esp]
	and	ebp,		eax
	xor	ebx,		DWORD PTR [esp]
	rol	ebx,		1
	mov	DWORD PTR 12[esp],ebx
	lea	ebx,		DWORD PTR 2400959708[ecx*1+ebx]
	mov	ecx,		edi
	ror	edi,		2
	and	ecx,		esi
	or	ebp,		ecx
	mov	ecx,		edx
	rol	ecx,		5
	add	ebp,		ecx
	add	ebx,		ebp
	; 40_59 52
	mov	ecx,		DWORD PTR 16[esp]
	mov	ebp,		edx
	xor	ecx,		DWORD PTR 24[esp]
	or	ebp,		edi
	xor	ecx,		DWORD PTR 48[esp]
	and	ebp,		esi
	xor	ecx,		DWORD PTR 4[esp]
	rol	ecx,		1
	mov	DWORD PTR 16[esp],ecx
	lea	ecx,		DWORD PTR 2400959708[eax*1+ecx]
	mov	eax,		edx
	ror	edx,		2
	and	eax,		edi
	or	ebp,		eax
	mov	eax,		ebx
	rol	eax,		5
	add	ebp,		eax
	add	ecx,		ebp
	; 40_59 53
	mov	eax,		DWORD PTR 20[esp]
	mov	ebp,		ebx
	xor	eax,		DWORD PTR 28[esp]
	or	ebp,		edx
	xor	eax,		DWORD PTR 52[esp]
	and	ebp,		edi
	xor	eax,		DWORD PTR 8[esp]
	rol	eax,		1
	mov	DWORD PTR 20[esp],eax
	lea	eax,		DWORD PTR 2400959708[esi*1+eax]
	mov	esi,		ebx
	ror	ebx,		2
	and	esi,		edx
	or	ebp,		esi
	mov	esi,		ecx
	rol	esi,		5
	add	ebp,		esi
	add	eax,		ebp
	; 40_59 54
	mov	esi,		DWORD PTR 24[esp]
	mov	ebp,		ecx
	xor	esi,		DWORD PTR 32[esp]
	or	ebp,		ebx
	xor	esi,		DWORD PTR 56[esp]
	and	ebp,		edx
	xor	esi,		DWORD PTR 12[esp]
	rol	esi,		1
	mov	DWORD PTR 24[esp],esi
	lea	esi,		DWORD PTR 2400959708[edi*1+esi]
	mov	edi,		ecx
	ror	ecx,		2
	and	edi,		ebx
	or	ebp,		edi
	mov	edi,		eax
	rol	edi,		5
	add	ebp,		edi
	add	esi,		ebp
	; 40_59 55
	mov	edi,		DWORD PTR 28[esp]
	mov	ebp,		eax
	xor	edi,		DWORD PTR 36[esp]
	or	ebp,		ecx
	xor	edi,		DWORD PTR 60[esp]
	and	ebp,		ebx
	xor	edi,		DWORD PTR 16[esp]
	rol	edi,		1
	mov	DWORD PTR 28[esp],edi
	lea	edi,		DWORD PTR 2400959708[edx*1+edi]
	mov	edx,		eax
	ror	eax,		2
	and	edx,		ecx
	or	ebp,		edx
	mov	edx,		esi
	rol	edx,		5
	add	ebp,		edx
	add	edi,		ebp
	; 40_59 56
	mov	edx,		DWORD PTR 32[esp]
	mov	ebp,		esi
	xor	edx,		DWORD PTR 40[esp]
	or	ebp,		eax
	xor	edx,		DWORD PTR [esp]
	and	ebp,		ecx
	xor	edx,		DWORD PTR 20[esp]
	rol	edx,		1
	mov	DWORD PTR 32[esp],edx
	lea	edx,		DWORD PTR 2400959708[ebx*1+edx]
	mov	ebx,		esi
	ror	esi,		2
	and	ebx,		eax
	or	ebp,		ebx
	mov	ebx,		edi
	rol	ebx,		5
	add	ebp,		ebx
	add	edx,		ebp
	; 40_59 57
	mov	ebx,		DWORD PTR 36[esp]
	mov	ebp,		edi
	xor	ebx,		DWORD PTR 44[esp]
	or	ebp,		esi
	xor	ebx,		DWORD PTR 4[esp]
	and	ebp,		eax
	xor	ebx,		DWORD PTR 24[esp]
	rol	ebx,		1
	mov	DWORD PTR 36[esp],ebx
	lea	ebx,		DWORD PTR 2400959708[ecx*1+ebx]
	mov	ecx,		edi
	ror	edi,		2
	and	ecx,		esi
	or	ebp,		ecx
	mov	ecx,		edx
	rol	ecx,		5
	add	ebp,		ecx
	add	ebx,		ebp
	; 40_59 58
	mov	ecx,		DWORD PTR 40[esp]
	mov	ebp,		edx
	xor	ecx,		DWORD PTR 48[esp]
	or	ebp,		edi
	xor	ecx,		DWORD PTR 8[esp]
	and	ebp,		esi
	xor	ecx,		DWORD PTR 28[esp]
	rol	ecx,		1
	mov	DWORD PTR 40[esp],ecx
	lea	ecx,		DWORD PTR 2400959708[eax*1+ecx]
	mov	eax,		edx
	ror	edx,		2
	and	eax,		edi
	or	ebp,		eax
	mov	eax,		ebx
	rol	eax,		5
	add	ebp,		eax
	add	ecx,		ebp
	; 40_59 59
	mov	eax,		DWORD PTR 44[esp]
	mov	ebp,		ebx
	xor	eax,		DWORD PTR 52[esp]
	or	ebp,		edx
	xor	eax,		DWORD PTR 12[esp]
	and	ebp,		edi
	xor	eax,		DWORD PTR 32[esp]
	rol	eax,		1
	mov	DWORD PTR 44[esp],eax
	lea	eax,		DWORD PTR 2400959708[esi*1+eax]
	mov	esi,		ebx
	ror	ebx,		2
	and	esi,		edx
	or	ebp,		esi
	mov	esi,		ecx
	rol	esi,		5
	add	ebp,		esi
	add	eax,		ebp
	; 20_39 60
	mov	esi,		DWORD PTR 48[esp]
	mov	ebp,		ecx
	xor	esi,		DWORD PTR 56[esp]
	ror	ecx,		2
	xor	esi,		DWORD PTR 16[esp]
	xor	ebp,		ebx
	xor	esi,		DWORD PTR 36[esp]
	xor	ebp,		edx
	rol	esi,		1
	mov	DWORD PTR 48[esp],esi
	lea	esi,		DWORD PTR 3395469782[edi*1+esi]
	mov	edi,		eax
	rol	edi,		5
	add	esi,		ebp
	add	esi,		edi
	; 20_39 61
	mov	edi,		DWORD PTR 52[esp]
	mov	ebp,		eax
	xor	edi,		DWORD PTR 60[esp]
	ror	eax,		2
	xor	edi,		DWORD PTR 20[esp]
	xor	ebp,		ecx
	xor	edi,		DWORD PTR 40[esp]
	xor	ebp,		ebx
	rol	edi,		1
	mov	DWORD PTR 52[esp],edi
	lea	edi,		DWORD PTR 3395469782[edx*1+edi]
	mov	edx,		esi
	rol	edx,		5
	add	edi,		ebp
	add	edi,		edx
	; 20_39 62
	mov	edx,		DWORD PTR 56[esp]
	mov	ebp,		esi
	xor	edx,		DWORD PTR [esp]
	ror	esi,		2
	xor	edx,		DWORD PTR 24[esp]
	xor	ebp,		eax
	xor	edx,		DWORD PTR 44[esp]
	xor	ebp,		ecx
	rol	edx,		1
	mov	DWORD PTR 56[esp],edx
	lea	edx,		DWORD PTR 3395469782[ebx*1+edx]
	mov	ebx,		edi
	rol	ebx,		5
	add	edx,		ebp
	add	edx,		ebx
	; 20_39 63
	mov	ebx,		DWORD PTR 60[esp]
	mov	ebp,		edi
	xor	ebx,		DWORD PTR 4[esp]
	ror	edi,		2
	xor	ebx,		DWORD PTR 28[esp]
	xor	ebp,		esi
	xor	ebx,		DWORD PTR 48[esp]
	xor	ebp,		eax
	rol	ebx,		1
	mov	DWORD PTR 60[esp],ebx
	lea	ebx,		DWORD PTR 3395469782[ecx*1+ebx]
	mov	ecx,		edx
	rol	ecx,		5
	add	ebx,		ebp
	add	ebx,		ecx
	; 20_39 64
	mov	ecx,		DWORD PTR [esp]
	mov	ebp,		edx
	xor	ecx,		DWORD PTR 8[esp]
	ror	edx,		2
	xor	ecx,		DWORD PTR 32[esp]
	xor	ebp,		edi
	xor	ecx,		DWORD PTR 52[esp]
	xor	ebp,		esi
	rol	ecx,		1
	mov	DWORD PTR [esp],ecx
	lea	ecx,		DWORD PTR 3395469782[eax*1+ecx]
	mov	eax,		ebx
	rol	eax,		5
	add	ecx,		ebp
	add	ecx,		eax
	; 20_39 65
	mov	eax,		DWORD PTR 4[esp]
	mov	ebp,		ebx
	xor	eax,		DWORD PTR 12[esp]
	ror	ebx,		2
	xor	eax,		DWORD PTR 36[esp]
	xor	ebp,		edx
	xor	eax,		DWORD PTR 56[esp]
	xor	ebp,		edi
	rol	eax,		1
	mov	DWORD PTR 4[esp],eax
	lea	eax,		DWORD PTR 3395469782[esi*1+eax]
	mov	esi,		ecx
	rol	esi,		5
	add	eax,		ebp
	add	eax,		esi
	; 20_39 66
	mov	esi,		DWORD PTR 8[esp]
	mov	ebp,		ecx
	xor	esi,		DWORD PTR 16[esp]
	ror	ecx,		2
	xor	esi,		DWORD PTR 40[esp]
	xor	ebp,		ebx
	xor	esi,		DWORD PTR 60[esp]
	xor	ebp,		edx
	rol	esi,		1
	mov	DWORD PTR 8[esp],esi
	lea	esi,		DWORD PTR 3395469782[edi*1+esi]
	mov	edi,		eax
	rol	edi,		5
	add	esi,		ebp
	add	esi,		edi
	; 20_39 67
	mov	edi,		DWORD PTR 12[esp]
	mov	ebp,		eax
	xor	edi,		DWORD PTR 20[esp]
	ror	eax,		2
	xor	edi,		DWORD PTR 44[esp]
	xor	ebp,		ecx
	xor	edi,		DWORD PTR [esp]
	xor	ebp,		ebx
	rol	edi,		1
	mov	DWORD PTR 12[esp],edi
	lea	edi,		DWORD PTR 3395469782[edx*1+edi]
	mov	edx,		esi
	rol	edx,		5
	add	edi,		ebp
	add	edi,		edx
	; 20_39 68
	mov	edx,		DWORD PTR 16[esp]
	mov	ebp,		esi
	xor	edx,		DWORD PTR 24[esp]
	ror	esi,		2
	xor	edx,		DWORD PTR 48[esp]
	xor	ebp,		eax
	xor	edx,		DWORD PTR 4[esp]
	xor	ebp,		ecx
	rol	edx,		1
	mov	DWORD PTR 16[esp],edx
	lea	edx,		DWORD PTR 3395469782[ebx*1+edx]
	mov	ebx,		edi
	rol	ebx,		5
	add	edx,		ebp
	add	edx,		ebx
	; 20_39 69
	mov	ebx,		DWORD PTR 20[esp]
	mov	ebp,		edi
	xor	ebx,		DWORD PTR 28[esp]
	ror	edi,		2
	xor	ebx,		DWORD PTR 52[esp]
	xor	ebp,		esi
	xor	ebx,		DWORD PTR 8[esp]
	xor	ebp,		eax
	rol	ebx,		1
	mov	DWORD PTR 20[esp],ebx
	lea	ebx,		DWORD PTR 3395469782[ecx*1+ebx]
	mov	ecx,		edx
	rol	ecx,		5
	add	ebx,		ebp
	add	ebx,		ecx
	; 20_39 70
	mov	ecx,		DWORD PTR 24[esp]
	mov	ebp,		edx
	xor	ecx,		DWORD PTR 32[esp]
	ror	edx,		2
	xor	ecx,		DWORD PTR 56[esp]
	xor	ebp,		edi
	xor	ecx,		DWORD PTR 12[esp]
	xor	ebp,		esi
	rol	ecx,		1
	mov	DWORD PTR 24[esp],ecx
	lea	ecx,		DWORD PTR 3395469782[eax*1+ecx]
	mov	eax,		ebx
	rol	eax,		5
	add	ecx,		ebp
	add	ecx,		eax
	; 20_39 71
	mov	eax,		DWORD PTR 28[esp]
	mov	ebp,		ebx
	xor	eax,		DWORD PTR 36[esp]
	ror	ebx,		2
	xor	eax,		DWORD PTR 60[esp]
	xor	ebp,		edx
	xor	eax,		DWORD PTR 16[esp]
	xor	ebp,		edi
	rol	eax,		1
	mov	DWORD PTR 28[esp],eax
	lea	eax,		DWORD PTR 3395469782[esi*1+eax]
	mov	esi,		ecx
	rol	esi,		5
	add	eax,		ebp
	add	eax,		esi
	; 20_39 72
	mov	esi,		DWORD PTR 32[esp]
	mov	ebp,		ecx
	xor	esi,		DWORD PTR 40[esp]
	ror	ecx,		2
	xor	esi,		DWORD PTR [esp]
	xor	ebp,		ebx
	xor	esi,		DWORD PTR 20[esp]
	xor	ebp,		edx
	rol	esi,		1
	mov	DWORD PTR 32[esp],esi
	lea	esi,		DWORD PTR 3395469782[edi*1+esi]
	mov	edi,		eax
	rol	edi,		5
	add	esi,		ebp
	add	esi,		edi
	; 20_39 73
	mov	edi,		DWORD PTR 36[esp]
	mov	ebp,		eax
	xor	edi,		DWORD PTR 44[esp]
	ror	eax,		2
	xor	edi,		DWORD PTR 4[esp]
	xor	ebp,		ecx
	xor	edi,		DWORD PTR 24[esp]
	xor	ebp,		ebx
	rol	edi,		1
	mov	DWORD PTR 36[esp],edi
	lea	edi,		DWORD PTR 3395469782[edx*1+edi]
	mov	edx,		esi
	rol	edx,		5
	add	edi,		ebp
	add	edi,		edx
	; 20_39 74
	mov	edx,		DWORD PTR 40[esp]
	mov	ebp,		esi
	xor	edx,		DWORD PTR 48[esp]
	ror	esi,		2
	xor	edx,		DWORD PTR 8[esp]
	xor	ebp,		eax
	xor	edx,		DWORD PTR 28[esp]
	xor	ebp,		ecx
	rol	edx,		1
	mov	DWORD PTR 40[esp],edx
	lea	edx,		DWORD PTR 3395469782[ebx*1+edx]
	mov	ebx,		edi
	rol	ebx,		5
	add	edx,		ebp
	add	edx,		ebx
	; 20_39 75
	mov	ebx,		DWORD PTR 44[esp]
	mov	ebp,		edi
	xor	ebx,		DWORD PTR 52[esp]
	ror	edi,		2
	xor	ebx,		DWORD PTR 12[esp]
	xor	ebp,		esi
	xor	ebx,		DWORD PTR 32[esp]
	xor	ebp,		eax
	rol	ebx,		1
	mov	DWORD PTR 44[esp],ebx
	lea	ebx,		DWORD PTR 3395469782[ecx*1+ebx]
	mov	ecx,		edx
	rol	ecx,		5
	add	ebx,		ebp
	add	ebx,		ecx
	; 20_39 76
	mov	ecx,		DWORD PTR 48[esp]
	mov	ebp,		edx
	xor	ecx,		DWORD PTR 56[esp]
	ror	edx,		2
	xor	ecx,		DWORD PTR 16[esp]
	xor	ebp,		edi
	xor	ecx,		DWORD PTR 36[esp]
	xor	ebp,		esi
	rol	ecx,		1
	mov	DWORD PTR 48[esp],ecx
	lea	ecx,		DWORD PTR 3395469782[eax*1+ecx]
	mov	eax,		ebx
	rol	eax,		5
	add	ecx,		ebp
	add	ecx,		eax
	; 20_39 77
	mov	eax,		DWORD PTR 52[esp]
	mov	ebp,		ebx
	xor	eax,		DWORD PTR 60[esp]
	ror	ebx,		2
	xor	eax,		DWORD PTR 20[esp]
	xor	ebp,		edx
	xor	eax,		DWORD PTR 40[esp]
	xor	ebp,		edi
	rol	eax,		1
	mov	DWORD PTR 52[esp],eax
	lea	eax,		DWORD PTR 3395469782[esi*1+eax]
	mov	esi,		ecx
	rol	esi,		5
	add	eax,		ebp
	add	eax,		esi
	; 20_39 78
	mov	esi,		DWORD PTR 56[esp]
	mov	ebp,		ecx
	xor	esi,		DWORD PTR [esp]
	ror	ecx,		2
	xor	esi,		DWORD PTR 24[esp]
	xor	ebp,		ebx
	xor	esi,		DWORD PTR 44[esp]
	xor	ebp,		edx
	rol	esi,		1
	mov	DWORD PTR 56[esp],esi
	lea	esi,		DWORD PTR 3395469782[edi*1+esi]
	mov	edi,		eax
	rol	edi,		5
	add	esi,		ebp
	add	esi,		edi
	; 20_39 79
	mov	edi,		DWORD PTR 60[esp]
	mov	ebp,		eax
	xor	edi,		DWORD PTR 4[esp]
	ror	eax,		2
	xor	edi,		DWORD PTR 28[esp]
	xor	ebp,		ecx
	xor	edi,		DWORD PTR 48[esp]
	xor	ebp,		ebx
	rol	edi,		1
	mov	DWORD PTR 60[esp],edi
	lea	edi,		DWORD PTR 3395469782[edx*1+edi]
	mov	edx,		esi
	rol	edx,		5
	add	edi,		ebp
	add	edi,		edx
	; End processing
	; 
	mov	ebp,		DWORD PTR 128[esp]
	mov	edx,		DWORD PTR 12[ebp]
	add	edx,		ecx
	mov	ecx,		DWORD PTR 4[ebp]
	add	ecx,		esi
	mov	esi,		eax
	mov	eax,		DWORD PTR [ebp]
	mov	DWORD PTR 12[ebp],edx
	add	eax,		edi
	mov	edi,		DWORD PTR 16[ebp]
	add	edi,		ebx
	mov	ebx,		DWORD PTR 8[ebp]
	add	ebx,		esi
	mov	DWORD PTR [ebp],eax
	mov	esi,		DWORD PTR 132[esp]
	mov	DWORD PTR 8[ebp],ebx
	add	esi,		64
	mov	eax,		DWORD PTR 68[esp]
	mov	DWORD PTR 16[ebp],edi
	cmp	esi,		eax
	mov	DWORD PTR 4[ebp],ecx
	jb	$L000start
	add	esp,		108
	pop	edi
	pop	ebx
	pop	ebp
	pop	esi
	ret
_sha1_block_asm_data_order ENDP
_TEXT	ENDS
_TEXT	SEGMENT
PUBLIC	_sha1_block_asm_host_order

_sha1_block_asm_host_order PROC NEAR
	mov	ecx,		DWORD PTR 12[esp]
	push	esi
	shl	ecx,		6
	mov	esi,		DWORD PTR 12[esp]
	push	ebp
	add	ecx,		esi
	push	ebx
	mov	ebp,		DWORD PTR 16[esp]
	push	edi
	mov	edx,		DWORD PTR 12[ebp]
	sub	esp,		108
	mov	edi,		DWORD PTR 16[ebp]
	mov	ebx,		DWORD PTR 8[ebp]
	mov	DWORD PTR 68[esp],ecx
	; First we need to setup the X array
	mov	eax,		DWORD PTR [esi]
	mov	ecx,		DWORD PTR 4[esi]
	mov	DWORD PTR [esp],eax
	mov	DWORD PTR 4[esp],ecx
	mov	eax,		DWORD PTR 8[esi]
	mov	ecx,		DWORD PTR 12[esi]
	mov	DWORD PTR 8[esp],eax
	mov	DWORD PTR 12[esp],ecx
	mov	eax,		DWORD PTR 16[esi]
	mov	ecx,		DWORD PTR 20[esi]
	mov	DWORD PTR 16[esp],eax
	mov	DWORD PTR 20[esp],ecx
	mov	eax,		DWORD PTR 24[esi]
	mov	ecx,		DWORD PTR 28[esi]
	mov	DWORD PTR 24[esp],eax
	mov	DWORD PTR 28[esp],ecx
	mov	eax,		DWORD PTR 32[esi]
	mov	ecx,		DWORD PTR 36[esi]
	mov	DWORD PTR 32[esp],eax
	mov	DWORD PTR 36[esp],ecx
	mov	eax,		DWORD PTR 40[esi]
	mov	ecx,		DWORD PTR 44[esi]
	mov	DWORD PTR 40[esp],eax
	mov	DWORD PTR 44[esp],ecx
	mov	eax,		DWORD PTR 48[esi]
	mov	ecx,		DWORD PTR 52[esi]
	mov	DWORD PTR 48[esp],eax
	mov	DWORD PTR 52[esp],ecx
	mov	eax,		DWORD PTR 56[esi]
	mov	ecx,		DWORD PTR 60[esi]
	mov	DWORD PTR 56[esp],eax
	mov	DWORD PTR 60[esp],ecx
	jmp	$L001shortcut
_sha1_block_asm_host_order ENDP
_TEXT	ENDS
END
